require('dotenv').config();
const express = require('express'), cors = require('cors'), helmet = require('helmet'), morgan = require('morgan'), rateLimit = require('express-rate-limit');
const connectDB = require('./config/db');
const { notFound, errorHandler, sanitize } = require('./middleware/error');
const app = express();
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(sanitize);
app.use(morgan('dev'));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, max: 500 }));
app.get('/api/health', (req, res) => res.json({ success: true, message: 'OK' }));
app.use('/api', require('./routes'));
app.use(notFound);
app.use(errorHandler);
const PORT = process.env.PORT || 5000;
connectDB().then(() => app.listen(PORT, () => console.log(`API running on http://localhost:${PORT}`))).catch(e => { console.error('MongoDB connection error:', e.message); process.exit(1); });
